meeting/urls.py
from django.urls import path
from .views import AddParticipantView, MeetingListView, MeetingDetailView, MeetingCreateView, MeetingUpdateView, MeetingDeleteView, \
    PersonnelListView, MeetingListByTagView, ScheduledParticipantsView, add_review, download_participants_list, generate_participant_list_pdf, participant_list, sarch_view, validate_presence

urlpatterns = [
    path('', MeetingListView.as_view(), name="aguipex-home"),
    path('meeting/<int:pk>/', MeetingDetailView.as_view(), name="meeting_detail"),
    path('meeting/new/', MeetingCreateView.as_view(), name="meeting_create"),
    path('meeting/<int:pk>/edit/', MeetingUpdateView.as_view(), name="meeting_update"),
    path('meeting/<int:pk>/delete/', MeetingDeleteView.as_view(), name='meeting_delete'),
    path('tag/<slug:slug>/', MeetingListByTagView.as_view(), name='meeting_list_by_tag'),
    path('personnels/', PersonnelListView.as_view(), name='aguipex-personnel'),
    path('meeting/<int:meeting_id>/add_review/', add_review, name='add_review'),
    path('meeting/<int:meeting_id>/validate_presence/', validate_presence, name='validate_presence'),
    path('recherche/', sarch_view, name="aguipex-search"),
    # path('download-model/', download_model, name='download_model_url'),
    path('meeting/<int:meeting_id>/participants/', participant_list, name='participant_list'),
    path('meeting/<int:meeting_id>/download_participant_list/', download_participants_list, name='download_participants_list'),
    path('meetings/<int:pk>/add_participant/', AddParticipantView.as_view(), name='add_participant'),
    path('meeting/<int:pk>/scheduled-participants/', ScheduledParticipantsView.as_view(), name='scheduled_participants'),
    path('meeting/<int:meeting_id>/participants/pdf/', generate_participant_list_pdf, name='participants_pdf'),







]

projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('aguipex-admin/', admin.site.urls),
    path('', include("meeting.urls")),
    path('personnel/', include("userauths.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += staticfiles_urlpatterns()

meeting/models.py
from datetime import timedelta
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from common.models import TimeStampedModel
from django.utils import timezone

User = get_user_model()

STATUS = (
    ('programmer', 'Programmer'),
    ('en_cours', 'En cours'),
    ('terminer', 'Terminer'),
)

RATING = (
    (1, '★✩✩✩✩'),
    (2, '★★✩✩✩'),
    (3, '★★★✩✩'),
    (4, '★★★★✩'),
    (5, '★★★★★'),
)


class Meeting(TimeStampedModel):
    title = models.CharField(verbose_name=_("Titre"), max_length=250)
    slug = AutoSlugField(populate_from="title", unique=True)
    body = models.TextField(verbose_name=_("Réunion"))
    tags = TaggableManager(blank=True)
    author = models.ForeignKey(User, verbose_name=_("Auteur"), on_delete=models.CASCADE, related_name="author_meetings")
    reporter = models.ForeignKey(User, verbose_name=_("Gestionnaire compte rendu"), on_delete=models.CASCADE,
                                 related_name="reporter_meetings")
    minutes_document = models.FileField(null=True, blank=True, verbose_name=_("Procès verbal"))
    date_debut = models.DateTimeField(blank=True, null=True)
    date_fin = models.DateTimeField(blank=True, null=True)
    meeting_status = models.CharField(choices=STATUS, max_length=15, default="programmer",
                                      verbose_name="Statut de la réunion")
    deadline_hours = models.IntegerField(verbose_name=_("Délai de soumission (heures)"), default=24)

    def __str__(self):
        return f"{self.title}"

    def save(self, *args, **kwargs):
        if not (
                self.author.is_superuser
                or self.author.is_staff
                # or self.author.profile.occupation == Profile.Occupation.RESPONSABLE
        ):
            raise ValueError(
                "Seuls les superutilisateurs ou les membres du personnel peuvent créer des réunions."
            )

        if self.date_fin:
            deadline = self.date_fin + timezone.timedelta(hours=self.deadline_hours)
            if self.reporter and timezone.now() > deadline:
                # Logique pour pénaliser le reporter ici
                print(f"Le reporter {self.reporter.username} a manqué le délai pour soumettre le rapport.")

        super().save(*args, **kwargs)

    def has_reporter_missed_deadline(self):
        if self.date_fin:
            deadline = self.date_fin + timezone.timedelta(hours=self.deadline_hours)
            return self.reporter and timezone.now() > deadline
        return False

    def duration(self):
        if self.date_debut and self.date_fin:
            duration = self.date_fin - self.date_debut
            hours, remainder = divmod(duration.total_seconds(), 3600)
            minutes = remainder // 60

            if int(hours) == 0:
                return f"{int(minutes)}min"
            else:
                return f"{int(hours)}h{int(minutes)}min"

        return "Durée indéterminée"
    
    def rapport_deadline(self):
        """
        Retourne la date et l'heure limite pour soumettre le rapport en tenant compte du délai de soumission
        et de la date de fin de la réunion.
        """
        if self.date_fin and self.deadline_hours is not None:
            deadline = self.date_fin + timedelta(hours=self.deadline_hours)
            return deadline
        return None

    def get_tags_display(self):
        return ", ".join(tag.name for tag in self.tags.all())

    class Meta:
        verbose_name = _("Réunion")
        verbose_name_plural = _("Réunions")


class Participation(TimeStampedModel):
    number_verify = models.CharField(max_length=50, unique=True, verbose_name=_("Numéro de participation"))
    participant = models.ForeignKey(User, verbose_name=_("Participant"), on_delete=models.CASCADE,
                                    related_name="participations")
    meeting = models.ForeignKey(Meeting, verbose_name=_("Réunion"), on_delete=models.CASCADE,
                                related_name="participations")
    status = models.CharField(max_length=10, choices=[('absent', 'Absent'), ('present', 'Présent')], default='absent')

    def __str__(self):
        return f"Le participant {self.participant.username} a le n° {self.number_verify} pour cette réunion"

    class Meta:
        verbose_name = _("Participation")
        verbose_name_plural = _("Participations")


class MeetingReview(TimeStampedModel):
    full_name = models.CharField(max_length=150, verbose_name="Nom complet")
    meeting = models.ForeignKey(Meeting, on_delete=models.SET_NULL, null=True, related_name="reviews",
                                verbose_name=_("Réunion"))
    review = models.TextField(verbose_name=_('Commentaire'))

    class Meta:
        verbose_name = _("Avis")
        verbose_name_plural = _("Avis sur les réunions")

    def __str__(self):
        return self.meeting.title


class Wishlist(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name="Personnel")
    meeting = models.ForeignKey(Meeting, on_delete=models.SET_NULL, null=True, related_name="wishlists",
                                verbose_name="Réunion")

    class Meta:
        verbose_name_plural = "Liste de favoris"

    def __str__(self):
        return self.meeting.title

meeting/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

from userauths.models import Profile
from .models import Meeting, MeetingReview, Participation
from .forms import MeetingForm

from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from django.conf import settings

from .forms import AddParticipantForm
from django.views import View
from django.db import IntegrityError

# from django.http import HttpResponse, Http404
# from django.conf import settings
# import os


class MeetingListView(LoginRequiredMixin, ListView):
    model = Meeting
    template_name = "meetings/acceuil.html"
    context_object_name = "meetings"
    paginate_by = 6
    login_url = 'userauths-sign-in'

    def get_queryset(self):
        return Meeting.objects.all().order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_meetings'] = Meeting.objects.count()
        return context

class MeetingDetailView(LoginRequiredMixin, DetailView):
    model = Meeting
    template_name = "meetings/meeting_detail.html"
    context_object_name = "meeting"
    login_url = 'userauths-sign-in'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_meetings'] = Meeting.objects.order_by('-created_at')[:6]
        context['all_tags'] = Tag.objects.all()
        context['participations'] = self.object.participations.select_related('participant')
        return context

class MeetingCreateView(LoginRequiredMixin, CreateView):
    model = Meeting
    form_class = MeetingForm
    template_name = "meetings/meeting_form.html"
    success_url = reverse_lazy("aguipex-home")
    login_url = 'userauths-sign-in'

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.success(self.request, "Réunion créée avec succès.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Erreur lors de la création de la réunion.")
        return super().form_invalid(form)

class MeetingUpdateView(LoginRequiredMixin, UpdateView):
    model = Meeting
    form_class = MeetingForm
    template_name = "meetings/meeting_form.html"
    success_url = reverse_lazy("aguipex-home")
    login_url = 'userauths-sign-in'

    def form_valid(self, form):
        messages.success(self.request, "Réunion mise à jour avec succès.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Erreur lors de la mise à jour de la réunion.")
        return super().form_invalid(form)

class MeetingDeleteView(LoginRequiredMixin, DeleteView):
    model = Meeting
    template_name = "meetings/meeting_confirm_delete.html"
    context_object_name = "meeting"
    success_url = reverse_lazy("aguipex-home")
    login_url = 'userauths-sign-in'

    def delete(self, request, *args, **kwargs):
        meeting = self.get_object()
        meeting.tags.clear()
        messages.success(self.request, "Réunion supprimée avec succès.")
        return super().delete(request, *args, **kwargs)

class MeetingListByTagView(LoginRequiredMixin, ListView):
    model = Meeting
    template_name = 'meetings/meeting_list_by_tag.html'
    context_object_name = 'meetings'
    login_url = 'userauths-sign-in'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        return Meeting.objects.filter(tags__slug=slug)

class PersonnelListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "meetings/personnels.html"
    context_object_name = "personnels"
    login_url = 'userauths-sign-in'

def add_review(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)

    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        review = request.POST.get('review')

        if full_name and review:
            MeetingReview.objects.create(
                full_name=full_name,
                meeting=meeting,
                review=review
            )
            messages.success(request, "Merci pour votre avis !")
        else:
            messages.error(request, "Veuillez remplir tous les champs.")

    return redirect('meeting_detail', pk=meeting_id)

# def add_review(request, meeting_id):
#     meeting = get_object_or_404(Meeting, pk=meeting_id)

#     if request.method == 'POST':
#         full_name = request.POST.get('full_name')
#         review = request.POST.get('review')

#         if full_name and review:
#             MeetingReview.objects.create(
#                 full_name=full_name,
#                 meeting=meeting,
#                 review=review
#             )
#             response = {'status': 'success', 'message': 'Merci pour votre avis !'}
#         else:
#             response = {'status': 'error', 'message': 'Veuillez remplir tous les champs.'}

#         return JsonResponse(response)

def validate_presence(request, meeting_id):
    if request.method == 'POST':
        meeting = get_object_or_404(Meeting, pk=meeting_id)
        participant_id = request.POST.get('participant')
        number_verify = request.POST.get('number_verify')

        try:
            participation = Participation.objects.get(
                meeting=meeting,
                participant_id=participant_id
            )
            if participation.number_verify != number_verify:
                return JsonResponse({'status': 'error', 'message': "Le numéro saisi ne vous appartient pas. Merci de vérifier ou de contacter l'admin."})
            elif participation.status == 'present':
                return JsonResponse({'status': 'error', 'message': "Vous avez déjà confirmé votre présence."})
            else:
                participation.status = 'present'
                participation.save()
                return JsonResponse({'status': 'success', 'message': "Merci pour votre présence."})
        except Participation.DoesNotExist:
            if Participation.objects.filter(number_verify=number_verify).exists():
                return JsonResponse({'status': 'error', 'message': "Le numéro est déjà utilisé."})
            else:
                return JsonResponse({'status': 'error', 'message': "Le numéro saisi ne vous appartient pas. Merci de vérifier ou de contacter l'admin."})

    return JsonResponse({'status': 'error', 'message': "Méthode non autorisée."})

def sarch_view(request):
    query = request.GET.get('q')
    meetings = Meeting.objects.filter(title__icontains=query).order_by('-created_at')
    context = {
        'query':query,
        'meetings':meetings
    }
    return render(request, 'meetings/search.html', context)



# def download_model(request):
#     file_path = os.path.join(settings.MEDIA_ROOT, 'modele', 'file.xlsx')
    
#     if os.path.exists(file_path):
#         with open(file_path, 'rb') as fh:
#             response = HttpResponse(fh.read(), content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
#             response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
#             return response
#     else:
#         raise Http404("Fichier non trouvé")

def participant_list(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    participants_present = Participation.objects.filter(meeting=meeting, status='present')
    
    return render(request, 'meetings/participant.html', {'participants_present': participants_present, 'meeting': meeting})


def download_participants_list(request, meeting_id):
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    participants_present = Participation.objects.filter(meeting=meeting, status='present')

    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="participants_meeting_{}.pdf"'.format(meeting_id)

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    # Title and header information
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, height - 50, f"Liste des participants pour la réunion: {meeting.title}")

    p.setFont("Helvetica", 12)
    p.drawString(100, height - 70, "MINISTERE DU COMMERCE DE L’INDUSTRIE ET DES PME")
    p.drawString(100, height - 90, "Conakry le………………..")
    p.drawString(100, height - 110, "Réf………….MCIPME/DGA/DG/AGUIPEX/2024")

    # Table headers
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, height - 140, "Nom")
    p.drawString(200, height - 140, "Email")
    p.drawString(350, height - 140, "Fonction")
    p.drawString(500, height - 140, "Téléphone")

    # Draw table lines
    p.line(50, height - 145, 550, height - 145)

    # Participants data
    y = height - 160
    p.setFont("Helvetica", 12)
    for participation in participants_present:
        p.drawString(50, y, participation.participant.profile.full_name)
        p.drawString(200, y, participation.participant.email)
        p.drawString(350, y, participation.participant.profile.fonction)
        p.drawString(500, y, participation.participant.profile.phone)
        y -= 20

    # Footer contact information
    p.setFont("Helvetica", 10)
    footer_y = 50
    p.drawString(100, footer_y, "Immeuble Horizon 3ème étage 5ème Avenue Sandervalia Commune de Kaloum")
    footer_y -= 15

templates/meetings/acceuil.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}
<title>Accueil | Bienvenue sur la plateforme de gestion de réunion AGUIPEX</title>
{% endblock title %}
{% block content %}
<div class="col-xl-9 col-lg-8 col-md-12">
    {% comment %} <div class="quicklink-sidebar-menu ctm-border-radius shadow-sm grow bg-white card">
        <div class="card-body d-flex justify-content-between align-items-center">
            <ul class="list-group list-group-horizontal-lg mb-0">
                <li class="list-group-item text-center active button-5">
                    <a href="{% url 'aguipex-home' %}" class="text-white">TOUTES LES REUNIONS</a>
                </li>
            </ul>
            
        </div>
    </div> {% endcomment %}
    
    <div class="card shadow-sm grow ctm-border-radius">
        <div class="card-body align-center">
            <h4 class="card-title float-left mb-0 mt-2">{{ total_meetings }} RÉUNIONS</h4>
            <ul class="nav nav-tabs float-right border-0 tab-list-emp">
                <li class="nav-item pl-3">
                {% if request.user.is_superuser %}
                    <a href="{% url 'meeting_create' %}" class="btn btn-theme button-1 text-white ctm-border-radius p-2 add-person ctm-btn-padding">
                        <i class="fa fa-plus"></i> Ajouter une réunion
                    </a>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        {% for meeting in meetings %}
        <div class="col-md-6">
            <div class="ctm-border-radius shadow-sm grow card">
                <div class="card-header">
                    <h4 class="card-title d-inline-block mb-0"><strong>{{ meeting.title|upper }}</strong></h4>
                    <div class="team-action-icon float-right mt-0">
                        {% if request.user.is_superuser %}
                        <span data-toggle="modal" data-target="#edit">
                            <a href="{% url 'meeting_update' meeting.pk %}" class="btn btn-theme text-white ctm-border-radius" title="Edit">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </span>
                        <span data-toggle="modal" data-target="#delete">
                            <a href="{% url 'meeting_delete' meeting.pk %}" class="btn btn-theme text-white ctm-border-radius" title="Delete">
                                <i class="fa fa-trash"></i>
                            </a>
                        </span>
                        {% endif %}
                    </div>
                    <p>
                        <strong class="text-primary"></strong> 
                        <span class="badge 
                            {% if meeting.meeting_status == 'programmer' %}
                                bg-danger
                            {% elif meeting.meeting_status == 'en_cours' %}
                                bg-primary
                            {% elif meeting.meeting_status == 'terminer' %}
                                bg-success
                            {% else %}
                                bg-secondary
                            {% endif %}
                        " style="color:#ffffff;">
                            {{ meeting.get_meeting_status_display|upper }}
                        </span>
                    </p>
                    {% if meeting.meeting_status == "programmer" %}
                    Le <span>{{meeting.date_debut}}</span>
                    {% else %}
                    C'était le <span>{{meeting.date_debut}}</span>
                    {% endif %}
                    
                </div>
                
                <div class="card-body">
                    {% comment %} <p class="card-text">{{ meeting.body|truncatechars:100 }}</p> {% endcomment %}

                    <span class="avatar bg-warning" data-toggle="tooltip" data-placement="top" title="{{ meeting.reporter.username }}">
                        <i class="fa fa-file"></i>
                        {% comment %} <img src="{% if meeting.reporter.profile.image %}{{ meeting.reporter.profile.image.url }}{% else %}{% static 'assets/img/profiles/default.png' %}{% endif %}" alt="{{ meeting.author.username }}" class="img-fluid"> {% endcomment %}
                    </span>
                    <a href="{% url 'meeting_detail' meeting.pk %}" class="btn btn-theme float-right ctm-border-radius text-white button-1" data-toggle="modal" data-target="#addmembers">Voir</a>
                    <p><strong class="text-primary"></strong> <span class="text-white badge badge-secondary" style="#ffffff; !important">{{meeting.reporter.profile.full_name }}</span></p>
                    <span>{{meeting.rapport_deadline}}</span>
                    {% if meeting.has_reporter_missed_deadline %}
                        <p class="text-danger" style="font-size:12px; font-weight:700px;">Le reporter <strong>{{ meeting.reporter.username }}</strong> a manqué le délai pour soumettre le rapport.</p>
                    {% endif %}

                </div>
            </div>
        </div>
        {% empty %}
            <p class="text-muted">Aucune réunion trouvée.</p>
        {% endfor %}
    </div>
    <div class="pagination">
        {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link text-primary" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Precedent</span>
                            </a>
                        </li>
                    {% endif %}
                    {% for num in paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link text-white bg-primary" href="#">{{ num }}</a></li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item"><a class="page-link text-primary" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link text-primary" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Suivant</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
    
</div>
{% endblock content %}

templates/meetings/add_participant.html
{% extends "partials/base.html" %}
{% block title %}
<title>Ajouter un participant | Bienvenue sur la plateforme de gestion de réunion AGUIPEX</title>
{% endblock title %}
{% block content %}
<div class="col-xl-9 col-lg-8 col-md-12">
    <div class="accordion add-employee" id="accordion-details">
      <div class="card shadow-sm grow ctm-border-radius">
        <div class="card-header" id="basic1">
          <h4 class="cursor-pointer mb-0">
            <a class="coll-arrow d-block text-dark" href="javascript:void(0)" data-toggle="collapse" data-target="#basic-one" aria-expanded="true">
              AJOÛT D'UN PARTICIPANT
              <br /><span class="ctm-text-sm">Ajouter un participant à la réunion {{ meeting.title }}</span>
            </a>
          </h4>
        </div>
        <div class="card-body p-0">
          <div id="basic-one" class="collapse show ctm-padding" aria-labelledby="basic1" data-parent="#accordion-details">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  <div class="col form-group">
                    {{ form.participant.label_tag }} 
                    {{ form.participant }}
                  </div>
                </div>
  
                <div class="col-md-6 form-group">
                  <div class="col form-group">
                    {{ form.number_verify.label_tag }}
                    <div class="cal-icon">
                      {{ form.number_verify }}
                    </div>
                  </div>
                </div>
                
              </div>
              <div class="row">
                <div class="col-12">
                  <div class="submit-section text-center btn-add">
                    <button class="btn btn-theme text-white ctm-border-radius button-1" type="submit">
                     Ajouter
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock content %}

templates/meetings/meeting_confirm_delete.html
{% extends "partials/base.html" %}
{% block title %}
<title>Supprimer une réunion | Bienvenue sur la plateforme de gestion de réunion AGUIPEX</title>
{% endblock title %}
{% block content %}
<div class="col-xl-4 col-lg-12 col-md-12 mx-auto mt-8">
    <div class="row">
        <div class="col-xl-12 col-lg-6 col-md-6 d-flex mx-auto">
            <div class="card ctm-border-radius shadow-sm grow flex-fill">
                <div class="card-header">
                    <h4 class="card-title mb-0">Voulez-vous supprimer cette réunion ?</h4>
                </div>
                <div class="card-body">
                    <p class="card-text mb-3">
                        <span class="text-primary">Titre: </span> {{ meeting.title }}
                    </p>
                    <div class="text-center">
                        <a href="{% url 'aguipex-home' %}" class="btn btn-theme ctm-border-radius text-white btn-sm">
                            Annuler
                        </a>
                        <form method="post" action="{% url 'meeting_delete' meeting.pk %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger ctm-border-radius text-white btn-sm">
                                Supprimer
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}